connector_image: airbyte/source-metabase:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_metabase/spec.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
      - config_path: "integration_tests/config_http_url.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
  incremental:
      bypass_reason: "This connector does not implement incremental sync"
