# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-monday:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_monday/spec.json"
  connection:
    tests:
      - config_path: "secrets/config_api_token.json"
        status: "succeed"
      - config_path: "secrets/config_oauth.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
      - config_path: "integration_tests/invalid_config_oauth.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config_api_token.json"
      - config_path: "secrets/config_oauth.json"
  basic_read:
    tests:
      - config_path: "secrets/config_api_token.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
          extra_fields: no
          exact_order: no
          extra_records: yes
        empty_streams:
          - name: updates
            bypass_reason: "unable to populate"
      - config_path: "secrets/config_oauth.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        expect_records:
          path: "integration_tests/expected_records.txt"
          extra_fields: no
          exact_order: no
          extra_records: yes
        empty_streams:
          - name: updates
            bypass_reason: "unable to populate"
  full_refresh:
    tests:
      - config_path: "secrets/config_api_token.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
